[package]
name = "rust-onedrive"
version = "0.1.0"
authors = ["sreeise"]
edition = "2018"
readme = "README.md"
license = "MIT"

[workspace]
members = [
    "graph-oauth",
]

[dependencies.url]
git = "https://github.com/servo/rust-url"
features = ["query_encoding"]

[dependencies]
serde = "1.0.88"
serde_json = "1.0.38"
serde_derive = "1.0.88"
reqwest = "0.9.6"
encoding = "0.2.33"
json = "0.11.13"
notify = "4.0.0"
base64 = "0.10.1"
graph-oauth = { path = "./graph-oauth" }

[badges]
travis-ci = { repository = "https://github.com/sreeise/rust-onedrive", branch = "master" }